export const fieldOptions= [
    { label: "域名", value: "domain" },
    { label: "CPU", value: "cpu_count" },
    { label: "磁盘", value: "disk_total" },
    { label: "内存", value: "mem_total" },
    { label: "正在充电", value: "batt_charging" },
    { label: "接口可用", value: "api_available" },
    { label: "接口锁定", value: "locked" },
    { label: "正在被控", value: "controlling" },
    { label: "品牌", value: "brand" },
    { label: "设备", value: "device" },
    { label: "型号", value: "model" },
    { label: "架构", value: "abi" },
    { label: "系统版本", value: "sdk" },
    { label: "硬件类型", value: "hardware" },
    { label: "板载类型", value: "board" },
    { label: "版本", value: "version" },
    { label: "启动时间", value: "boot_time" },
    { label: "注册时间", value: "reg_time" },
    { label: "备注", value: "comment" },
    { label: "状态", value: "state" },
]